[package]
name = "boot_stub"
version = "1.0.0"
edition = "2021"

[build-dependencies]
cc = "1.0"

[dependencies]
shared = { path = "../../shared" }
bitflags = "2"
kernel_log = { path = "../log" }

[profile.release]
panic = "abort"
opt-level = 2
lto = true
codegen-units = 1
